name: Selenium tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5' # run every weekdays 5am

jobs:
  swag_lab_test_site_selenium-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master # checkout code only from the 'master' branch
      - name: Install the dependencies...
        run: npm install
      - name: Install mocha js dependencies...
        run: npm install -g mocha
      - name: Install selenium webdriver...
        run: npm install selenium-webdriver
      - name: Run the swag lab web page test...
        run: npm run selenium:mocha
