name: Selenium tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5' # run every weekdays 5am

jobs:
  swagger_selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master # checkout code only from the 'master' branch
      - name: Install virtual display...
        run: sudo apt-get install -y xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable imagemagick x11-apps libgtk-3-0
      - name: Set up virtual display
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
      - name: Install the dependencies...
        run: npm install
      - name: Install mocha js dependencies...
        run: npm install -g mocha
      - name: Install selenium webdriver...
        run: npm install selenium-webdriver
      - name: Run the swagger test...
        run: npm run selenium:mocha
