name: Selenium tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5' # run every weekdays 5am

jobs:
  swagger_selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master # checkout code only from the 'master' branch
      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install the dependencies...
        run: npm install
      - name: Install mocha js dependencies...
        run: npm install -g mocha
      - name: Install selenium webdriver...
        run: npm install selenium-webdriver
      - name: Run the swagger test...
        run: npm run selenium:mocha
